# Generated by Django 4.2.30 on 2026-05-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_row_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("source_category", models.CharField(max_length=128)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("scope1", "Scope 1"),
                            ("scope2", "Scope 2"),
                            ("scope3", "Scope 3"),
                        ],
                        max_length=16,
                    ),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("activity_description", models.CharField(blank=True, max_length=256)),
                ("original_properties", models.JSONField(default=dict)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("quantity_unit", models.CharField(blank=True, max_length=32)),
                ("normalized_quantity", models.FloatField(blank=True, null=True)),
                ("normalized_unit", models.CharField(blank=True, max_length=32)),
                ("emission_factor", models.FloatField(blank=True, null=True)),
                ("emissions_kg_co2e", models.FloatField(blank=True, null=True)),
                ("suspicious_reason", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=128)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("edited_by", models.CharField(blank=True, max_length=128)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap_fuel", "SAP Fuel / Procurement"),
                            ("utility_electricity", "Utility Electricity"),
                            ("travel", "Corporate Travel"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "origin_file_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="ingestion.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmissionRowAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_type", models.CharField(max_length=64)),
                ("changed_by", models.CharField(blank=True, max_length=128)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(default=dict)),
                (
                    "emission_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="ingestion.emissionrow",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="emissionrow",
            name="ingestion_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to="ingestion.ingestionsource",
            ),
        ),
        migrations.AddField(
            model_name="emissionrow",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emissions",
                to="ingestion.tenant",
            ),
        ),
    ]
