# Generated by Django 4.2.30 on 2026-05-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_default_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Lookup key, e.g. diesel_l, electricity_kwh, flight_economy_km",
                        max_length=64,
                    ),
                ),
                ("factor", models.FloatField(help_text="kg CO2e per unit")),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_factors",
                        to="ingestion.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "key")},
            },
        ),
    ]
